version: "3.8"
services:

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: devotel/user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"

  profile-service:
    build:
      context: .
      dockerfile: profile-service/Dockerfile
    image: devotel/profile-service:latest
    container_name: profile-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URI=http://user-service:8081/ws