version: "3.8"

services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: devotel/user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - devotel-network

  profile-service:
    build:
      context: .
      dockerfile: profile-service/Dockerfile
    image: devotel/profile-service:latest
    container_name: profile-service
    depends_on:
      - user-service
    ports:
      - "8082:8082"
    networks:
      - devotel-network

networks:
  devotel-network:
    driver: bridge