server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:profilesdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

soap:
  client:
    uri: ${USER_SERVICE_URI:http://localhost:8081/ws}